### ISSUE TITLE
paper is very short

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/hid-sp18-517#2]

**Comment by harshadpitkar** [comment]
Added new sections to the paper. Performed checks using chktex, no errors or warnings reported.

$ chktex -n 13 -n 8 -n 29 content.tex 
ChkTeX v1.7.4 - Copyright 1995-96 Jens T. Berger Thielemann.
Compiled with PCRE regex support.
No errors printed; No warnings printed; 2 user suppressed warnings; No line suppressed warnings.

Checked for non-ascii characters, none found.

$ perl -ane "{ if(m/[[:^ascii:]]/) { print  } }" report.bib
$ perl -ane "{ if(m/[[:^ascii:]]/) { print  } }" content.tex
